title: IFCA Computing status page
languageCode: en
params:
  shortDateFormat: 15:04 — Jan 2
  meta_description: This status page provides updated information about our
    systems normal operation, incidents that may happen and their resolution.
  systems:
    - name: Batch System
      description: Slurm batch system for Altamira
      group: Altamira supercomputer
    - name: Login nodes
      description: Altamira login nodes (login1, login2)
      group: Altamira supercomputer
    - name: OpenStack Cloud Public APIs
      description: null
      group: Cloud Infrastructure
    - name: OpenStack Compute (nova)
      description: null
      group: Cloud Infrastructure
      link: https://api.cloud.ifca.es:8774/
    - name: OpenStack Identity (Keystone)
      description: null
      group: Cloud Infrastructure
      link: https://api.cloud.ifca.es:5000/
    - name: OpenStack Object Storage (Swift)
      description: null
      group: Cloud Infrastructure
      link: https://api.cloud.ifca.es:8080/
    - name: OpenStack Block Storage (cinder)
      description: null
      group: Cloud Infrastructure
      link: https://api.cloud.ifca.es:8776/
    - name: OpenStack Image catalalog (Glance)
      description: null
      group: Cloud Infrastructure
      link: https://api.cloud.ifca.es:9292/
    - name: OpenStack Networking (Neutron)
      description: null
      group: Cloud Infrastructure
      link: https://api.cloud.ifca.es:9696/
    - name: User Interfaces
      description: null
      group: Grid and HTC
    - name: Computing Elements
      description: null
      group: Grid and HTC
    - name: Indico Agenda pages
      description: null
      group: Web and miscelaneous services
      link: https://indico.ifca.es/
    - name: Wordpress pages
      description: null
      group: Web and miscelaneous services
      link: https://wordpress.ifca.es/
    - name: Wiki (Confluence)
      description: null
      group: Web and miscelaneous services
      link: https://confluence.ifca.es/
    - name: Videoconference system
      group: Web and miscelaneous services
      link: https://talk.ifca.es/
    - name: Chat rooms
      group: Web and miscelaneous services
      link: https://meet.ifca.es/
    - name: GitLab
      group: Web and miscelaneous services
      link: https://gitlab.ifca.es/
    - name: IFCA repository mirror
      group: Web and miscelaneous services
      link: https://repo.ifca.es/
    - name: Data Science Hub
      group: Web and miscelaneous services
      link: https://datasciencehub.ifca.es/
    - name: Helpdesk
      group: Web and miscelaneous services
      link: https://support.ifca.es
    - name: Monitoring
      group: Web and miscelaneous services
      link: https://monitor.ifca.es
    - name: Authentication Single Sign-on
      group: Authentication system
      link: https://sso.ifca.es
    - name: Authentication main system
      group: Authentication system
      link: https://auth01.ifca.es
    - name: Authentication replica
      group: Authentication system
      link: https://auth02.ifca.es
    - name: External network connection
      group: Networking
    - name: Internal networking
      group: Networking
    - name: Backup system
      group: Storage systems
    - name: Ceph block storage
      group: Storage systems
    - name: IBM Spectrum Scale
      group: Storage systems
    - name: Tape system
      group: Storage systems
    - name: DNS
      group: Networking
    - name: OpenStack Dashboard (Horizon)
      group: Cloud Infrastructure
      link: https://portal.cloud.ifca.es
    - name: OpenStack Compute Nodes
      group: Cloud Infrastructure
  dateFormat: January 2, 2006 at 15:04
  disqusShortname: null
  timezoneString: " UTC"
  logo: /images/logo.png
  description_header: >-
    Please refer to this page in order to get the most accurate status of the
    available resources of the IFCA <a class='text-grey-darkest' title='IFCA
    Advanced Computing and e-Science group'
    href='https://computing.ifca.es/'>Advanced Computing and e-Science
    group</a>.


    <br />Follow us <a class='text-grey-darkest' title='Visit our page on Twitter' href='https://www.twitter.com/IFCA_Computing'>on Twitter</a> or subscribe to <a class='text-grey-darkest' href='%s' >RSS</a><br />to be alerted of new events.
  copyrightHolder: ""
  eventsPerPage: 10
  groups:
    - Networking
    - Authentication system
    - Cloud Infrastructure
    - Storage systems
    - Altamira supercomputer
    - Grid and HTC
    - Web and miscelaneous services
  icon: /images/favicon.ico
  description_footer: <a class='text-grey-darkest' title='IFCA Advanced Computing
    and e-Science group' href='https://computing.ifca.es/'>IFCA Advanced
    Computing and e-Science group</a>.
